<a href="https://colab.research.google.com/github/MiguelAguilera/Neuro-MaxEnt-inference-tutorial/blob/main/Spike_train_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
# !pip install requests
import requests
# Save datagenerators as file to colab working directory
# If you are using GitHub, make sure you get the "Raw" version of the code
url = 'https://raw.githubusercontent.com/MiguelAguilera/Neuro-MaxEnt-inference-tutorial/main/Ising.py'
r = requests.get(url)

# make sure your filename is the same as how you want to import 
with open('Ising.py', 'w') as f:
    f.write(r.text)

# now we can import
from Ising import Ising


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [11]:
I = Ising(10)

for i in range(10):
  I.MetropolisStep()
  print(I.s)

[ 1 -1  1 -1 -1 -1 -1  1 -1  1]
[ 1  1  1 -1 -1 -1 -1  1 -1  1]
[ 1  1  1 -1 -1  1 -1  1 -1  1]
[ 1  1  1  1 -1  1 -1  1 -1  1]
[ 1  1  1  1 -1  1 -1 -1 -1  1]
[ 1  1  1  1 -1  1  1 -1 -1  1]
[ 1  1  1  1 -1  1  1 -1  1  1]
[ 1  1  1  1 -1  1 -1 -1  1  1]
[ 1  1  1  1 -1  1 -1 -1 -1  1]
[ 1  1  1  1 -1  1 -1 -1 -1 -1]
